import jsPDF from 'jspdf'
import 'jspdf-autotable'

interface ReportData {
  title: string
  description: string
  columns: string[]
  data: Record<string, any>[]
  summary?: Record<string, any>
}

interface ReportPDFOptions {
  reportData: ReportData
  dateRange: {
    startDate: string
    endDate: string
  }
  companyName?: string
  companyLogo?: string
}

export async function generateReportPDF(options: ReportPDFOptions): Promise<void> {
  try {
    const {
      reportData,
      dateRange,
      companyName = 'IRMS',
      companyLogo,
    } = options

    console.log('PDF Generation - Input data:', {
      hasReportData: !!reportData,
      hasColumns: !!reportData?.columns,
      columnsLength: reportData?.columns?.length,
      hasData: !!reportData?.data,
      dataLength: reportData?.data?.length,
    })

    // Validate reportData
    if (!reportData) {
      throw new Error('Report data is required')
    }

    if (!reportData.columns || reportData.columns.length === 0) {
      throw new Error('Report columns are missing')
    }

    if (!reportData.data) {
      throw new Error('Report data is missing')
    }

    const doc = new jsPDF()
    let yPosition = 20

    // Header with company logo and details
    if (companyLogo) {
      try {
        doc.addImage(companyLogo, 'PNG', 15, yPosition, 30, 30)
      } catch (e) {
        console.warn('Failed to add company logo to PDF')
      }
    }

    // Company name and title
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(companyName, companyLogo ? 50 : 15, yPosition + 10)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('Financial Report', companyLogo ? 50 : 15, yPosition + 18)

    // Report metadata
    yPosition += 40
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text('Report Details:', 15, yPosition)

    yPosition += 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.text(`Report: ${reportData.title || 'N/A'}`, 15, yPosition)
    yPosition += 5
    doc.text(`Description: ${reportData.description || 'N/A'}`, 15, yPosition)
    yPosition += 5
    doc.text(
      `Date Range: ${new Date(dateRange.startDate).toLocaleDateString()} — ${new Date(dateRange.endDate).toLocaleDateString()}`,
      15,
      yPosition
    )
    yPosition += 5
    doc.text(`Generated: ${new Date().toLocaleString()}`, 15, yPosition)
    yPosition += 5
    doc.text(`Total Records: ${reportData.data?.length || 0}`, 15, yPosition)

    // Summary section
    if (reportData.summary && Object.keys(reportData.summary).length > 0) {
      yPosition += 10
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.text('Summary:', 15, yPosition)

      yPosition += 6
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)

      Object.entries(reportData.summary).forEach(([key, value]) => {
        doc.text(`${key}: ${formatSummaryValue(value)}`, 20, yPosition)
        yPosition += 5
      })
    }

    // Data table
    yPosition += 5

    // Only create table if there's data
    if (reportData.data.length > 0) {
      const tableData = reportData.data.map((row) =>
        reportData.columns.map((col) => formatTableValue(row[col]))
      )

      const jsPDFWithPlugin = doc as any
      jsPDFWithPlugin.autoTable({
        head: [reportData.columns],
        body: tableData,
        startY: yPosition,
        margin: { top: 10, right: 15, bottom: 15, left: 15 },
        headStyles: {
          fillColor: [188, 0, 4], // Brand red color
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 9,
          halign: 'left',
        },
        bodyStyles: {
          fontSize: 8,
          textColor: [51, 51, 51],
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
        didDrawPage: (data: any) => {
          // Footer
          const pageCount = jsPDFWithPlugin.internal.getNumberOfPages()
          const pageSize = doc.internal.pageSize
          const pageHeight = pageSize.getHeight()
          const pageWidth = pageSize.getWidth()

          doc.setFontSize(8)
          doc.setTextColor(128, 128, 128)
          doc.text(
            `Page ${data.pageNumber} of ${pageCount}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
          )

          // Company footer
          doc.setFontSize(7)
          doc.text(
            'This is an official financial report generated by IRMS.',
            15,
            pageHeight - 5
          )
        },
      })
    } else {
      // No data message
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text('No data available for this report', 15, yPosition)
    }

    // Save the PDF
    const fileName = `report-${reportData.title.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(fileName)
  } catch (error) {
    console.error('Error generating PDF:', error)
    throw error
  }
}

function formatTableValue(value: any): string {
  if (value === null || value === undefined) return '-'
  if (typeof value === 'number') {
    if (value > 1000) {
      return new Intl.NumberFormat('en-NG', {
        style: 'currency',
        currency: 'NGN',
        minimumFractionDigits: 0,
      }).format(value)
    }
    return value.toString()
  }
  return String(value)
}

function formatSummaryValue(value: any): string {
  if (value === null || value === undefined) return '-'
  if (typeof value === 'number') {
    if (value > 1000) {
      return new Intl.NumberFormat('en-NG', {
        style: 'currency',
        currency: 'NGN',
        minimumFractionDigits: 0,
      }).format(value)
    }
    return value.toString()
  }
  return String(value)
}
